#ifndef INC_VERSION_H_
#define INC_VERSION_H_

#define VERSION_MAJOR 0
#define VERSION_MINOR 0

#define VERSION_DATE_YEAR 0000
#define VERSION_DATE_MONTH 00
#define VERSION_DATE_DAY 00

#define VERSION_TIME_HOUR 00
#define VERSION_TIME_MINUTE 00
#define VERSION_TIME_SECOND 00

#define VERSION_COMP_NUMBER 00

#endif /* INC_VERSION_H_ */
